const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {Miniflare}=require(process.env.TEST_MINIFLARE_MODULE||'miniflare');
const {chromium}=require('playwright');
const qr=require(process.env.TEST_QRCODE_MODULE||'qrcode');
const root=path.resolve(__dirname,'..'),origin='http://127.0.0.1:4190';
const secret='local-test-only-secret-not-used-on-the-live-site';
const valid={name:'Alex Integration',email:'alex@example.test',phone:'09171234567',password:'TestingPassword2026!',plan:'plus',goal:'Build strength'};
(async()=>{
 const mf=new Miniflare({modules:true,modulesRules:[{type:'ESModule',include:['**/*.js']}],scriptPath:path.join(root,'src/worker.js'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{OWNER_ID:'test-owner',OWNER_EMAIL:'owner@example.test',APP_SECRET:secret}});
 let browser,server;
 const request=async(endpoint,{body,cookie,owner=false,originHeader=origin}={})=>{const r=await mf.dispatchFetch(origin+'/api'+endpoint,{method:body===undefined?'GET':'POST',headers:{...(body!==undefined?{'content-type':'application/json','Origin':originHeader}:{}),...(owner?{'oai-authenticated-user-id':'test-owner'}:{}),...(cookie?{Cookie:cookie}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return{status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:await r.json()};};
 try{
 assert.equal((await request('/state')).status,401);
 assert.equal((await request('/owner-login',{body:{}})).status,403);
 assert.equal((await request('/owner-login',{body:{},owner:true,originHeader:'https://evil.invalid'})).status,403);
 const admin=await request('/owner-login',{body:{},owner:true});assert.equal(admin.status,200,JSON.stringify(admin.data));
 const clock=(await request('/session')).data.date;
 assert.equal((await request('/signup',{body:{...valid,phone:''}})).status,400);
 assert.equal((await request('/signup',{body:{...valid,phone:'12345'}})).status,400);
 assert.equal((await request('/signup',{body:{...valid,plan:'free'}})).status,400);
 const signup=await request('/signup',{body:{...valid,amount:1}});assert.equal(signup.status,201,JSON.stringify(signup.data));
 const memberCookie=signup.cookie;
 const duplicate=await request('/signup',{body:valid});assert.equal(duplicate.status,409);
 const memberState=(await request('/state',{cookie:memberCookie})).data;
 assert.equal(memberState.members.length,1);assert.equal(memberState.invoices[0].amount,1499);assert.equal(memberState.outbox.length,0);
 const invoiceId=memberState.invoices[0].id;
 assert.equal((await request('/payments',{cookie:memberCookie,body:{invoiceId,amount:1499,method:'Cash',verified:true}})).status,403);
 assert.equal((await request('/settings/payments',{cookie:memberCookie,body:{}})).status,403);
 assert.equal((await request('/scan',{cookie:memberCookie,body:{token:'x'}})).status,403);
 const adminAdd=await request('/members',{cookie:admin.cookie,body:{...valid,email:'second@example.test',name:'Second Member',plan:'basic'}});assert.equal(adminAdd.status,201);
 assert.equal((await request('/state',{cookie:memberCookie})).data.members.length,1);
 const invoice=(await request('/state',{cookie:admin.cookie})).data.invoices.find(i=>i.id===invoiceId);
 const payment={invoiceId,amount:1000,method:'Cash',date:clock,reference:'',verified:true,idempotencyKey:crypto.randomUUID()};
 assert.equal((await request('/payments',{cookie:admin.cookie,body:{...payment,amount:1500}})).status,400);
 assert.equal((await request('/payments',{cookie:admin.cookie,body:{...payment,verified:false}})).status,400);
 assert.equal((await request('/payments',{cookie:admin.cookie,body:payment})).status,201);
 assert.equal((await request('/payments',{cookie:admin.cookie,body:payment})).status,400);
 const pendingQR=(await request('/qr',{cookie:memberCookie})).data;
 assert.equal((await request('/scan',{cookie:admin.cookie,body:{token:pendingQR.token}})).status,400);
 // Real QR assets are only replaced with a local test fixture in this isolated database.
 const image=await qr.toDataURL('LOCAL TEST FIXTURE — NOT A PAYMENT DESTINATION');
 assert.equal((await request('/settings/payments',{cookie:admin.cookie,body:{gcash:{image,name:'Local Test Recipient',detail:'Test only'},bank:{image,name:'Local Test Bank Recipient',detail:'Test bank only'}}})).status,200);
 const submitted=await request('/payment-submissions',{cookie:memberCookie,body:{invoiceId,amount:499,method:'GCash',reference:'LOCAL-REF-001'}});assert.equal(submitted.status,201,JSON.stringify(submitted.data));
 const repeat=await request('/payment-submissions',{cookie:memberCookie,body:{invoiceId,amount:499,method:'GCash',reference:'LOCAL-REF-001'}});assert.equal(repeat.status,409);
 assert.equal((await request('/review-payment',{cookie:admin.cookie,body:{id:submitted.data.submission.id,approve:true,verified:false}})).status,400);
 assert.equal((await request('/review-payment',{cookie:admin.cookie,body:{id:submitted.data.submission.id,approve:true,verified:true}})).status,200);
 assert.equal((await request('/review-payment',{cookie:admin.cookie,body:{id:submitted.data.submission.id,approve:true,verified:true}})).status,409);
 const pass=(await request('/qr',{cookie:memberCookie})).data;
 assert.equal((await request('/scan',{cookie:admin.cookie,body:{token:pass.token}})).status,200);
 const tampered=pass.token.slice(0,-3)+'AAA';assert.equal((await request('/scan',{cookie:admin.cookie,body:{token:tampered}})).status,400);
 const payload=Buffer.from(JSON.stringify({memberId:signup.data.memberId,exp:Math.floor(Date.now()/1000)-60,nonce:'expired-fixture'})).toString('base64');
 const expired='FORM1.'+payload+'.'+crypto.createHmac('sha256',secret).update(payload).digest('base64');assert.equal((await request('/scan',{cookie:admin.cookie,body:{token:expired}})).status,400);
 assert.equal((await request('/check-in',{cookie:admin.cookie,body:{token:pass.token,confirmed:false}})).status,400);
 assert.equal((await request('/check-in',{cookie:admin.cookie,body:{token:pass.token,confirmed:true}})).status,201);
 assert.equal((await request('/check-in',{cookie:admin.cookie,body:{token:pass.token,confirmed:true}})).status,409);
 const ds=(await request('/state',{cookie:admin.cookie})).data;assert(ds.outbox.length>=5);assert(ds.outbox.every(m=>m.status==='queued'));assert.equal(ds.settings.email.connected,false);
 assert.equal((await request('/email-retry',{cookie:admin.cookie,body:{}})).status,400);
 const db=await mf.getD1Database('DB');const account=await db.prepare('SELECT * FROM accounts WHERE email=?').bind(valid.email).first();assert.equal(account.password_hash.length,64);assert.notEqual(account.password_hash,valid.password);
 assert.equal((await request('/logout',{cookie:memberCookie,body:{}})).status,200);
 assert.equal((await request('/state',{cookie:memberCookie})).status,401);
 assert.equal((await request('/login',{body:{email:valid.email,password:'wrong'}})).status,401);
 const login=await request('/login',{body:{email:valid.email,password:valid.password}});assert.equal(login.status,200);
 console.log('PASS API: required contacts, authoritative plans/prices, signup/login/logout, role isolation, partial payment, overpayment/duplicate protections, payment review, signed/expired/replayed QR passes, identity confirmation, hashed passwords, queued email status.');
 // Browser requests pass through a local test proxy that supplies a test owner identity.
 server=http.createServer(async(req,res)=>{try{if(req.url.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const headers={...req.headers,'oai-authenticated-user-id':'test-owner'};delete headers.host;delete headers['content-length'];const r=await mf.dispatchFetch(origin+req.url,{method:req.method,headers,...(req.method==='POST'?{body:Buffer.concat(chunks)}:{})});res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));}else{const file=path.join(root,'public',req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(path.join(root,'public')+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(file));}}catch(e){res.writeHead(500).end(String(e));}});
 await new Promise(r=>server.listen(4190,'127.0.0.1',r));
 browser=await chromium.launch({headless:true,...(process.env.TEST_BROWSER?{executablePath:process.env.TEST_BROWSER}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const heading=async(name)=>page.getByRole('heading',{name,exact:true}).waitFor();
 const snap=async(name)=>{if(process.env.TEST_SCREENSHOTS){fs.mkdirSync(process.env.TEST_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.TEST_SCREENSHOTS,name+'.png'),fullPage:true,animations:'disabled'});}};
 await page.goto(origin);await heading('Good to see you.');await snap('connected-sign-in');
 await page.getByRole('button',{name:'Create a member account',exact:true}).click();await page.getByLabel('Full name *',{exact:true}).fill('Browser Member');await page.getByLabel('Email address *',{exact:true}).fill('browser@example.test');await page.getByLabel('Create password *',{exact:true}).fill('BrowserPassword2026!');
 await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.locator('#phone').evaluate(el=>el.validity.valueMissing),true);
 await page.getByLabel('Mobile number *',{exact:true}).fill('12345');await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.locator('.step.active').textContent(),'1Member details');
 await page.getByLabel('Mobile number *',{exact:true}).fill('09179876543');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('#confirm-details').check();await page.getByRole('button',{name:'Create member',exact:true}).click();await heading('Welcome to FORM.');await page.getByRole('button',{name:'Done',exact:true}).click();await heading('Your next chapter, Browser.');await snap('connected-member');
 await page.getByRole('button',{name:'Pay by QR',exact:true}).click();await heading('Pay your membership');assert.equal(await page.locator('.payment-qr img').count(),1);await snap('connected-payment-qr');await page.getByRole('button',{name:'Bank transfer',exact:true}).click();assert.match(await page.locator('.payment-qr').textContent(),/Local Test Bank Recipient/);await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Log out',exact:true}).click();await heading('Good to see you.');
 await page.getByLabel('Email address',{exact:true}).fill(valid.email);await page.getByLabel('Password',{exact:true}).fill(valid.password);await page.getByRole('button',{name:'Log in',exact:true}).click();await heading('Your next chapter, Alex.');await page.getByRole('button',{name:'Show my member QR',exact:true}).click();await heading('Your member QR');await snap('connected-live-pass');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.reload();await heading('Your next chapter, Alex.');
 const freshPass=await page.evaluate(()=>fetch('/api/qr').then(r=>r.json()));assert(freshPass.token);
 const qrBytes=await qr.toBuffer(freshPass.token,{width:500,margin:2});
 await page.getByRole('button',{name:'Log out',exact:true}).click();await heading('Good to see you.');await page.getByRole('button',{name:'Admin sign in',exact:true}).click();await heading('A stronger community.');await snap('connected-dashboard');
 await page.getByRole('button',{name:'Scan member',exact:true}).click();await heading('Verify a member');await page.locator('#scan-file').setInputFiles({name:'member-pass.png',mimeType:'image/png',buffer:qrBytes});await heading('Membership verified');await snap('connected-scanner-result');await page.locator('#identity-confirmed').check();await page.getByRole('button',{name:'Confirm check-in',exact:true}).click();await page.locator('[role="dialog"]').waitFor({state:'detached'});
 await page.getByRole('button',{name:'Open settings',exact:true}).click();await heading('Workspace settings');await page.getByRole('button',{name:'Gmail sender',exact:true}).click();assert.match(await page.locator('.connection-status').textContent(),/not connected/);await snap('connected-gmail-settings');await page.getByRole('button',{name:'Notifications',exact:true}).click();assert.match(await page.locator('.modal').textContent(),/Queued/);await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await snap('connected-mobile-admin');await page.getByRole('button',{name:'Log out',exact:true}).click();await heading('Good to see you.');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await snap('connected-mobile-login');
 assert.deepEqual(errors,[]);
 console.log('PASS BROWSER: sign-up contact validation, plan registration, login/logout, cookie persistence, actual uploaded QR display, QR generation and image scanning, identity-confirmed check-in, Gmail configuration status, notification log, and responsive layouts.');
 }finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await mf.dispose();}
})().catch(e=>{console.error(e);process.exitCode=1;});
