const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');

// Run with `node tests/flows.cjs`. TEST_BROWSER optionally selects an installed Chromium.
(async()=>{
 const root=path.resolve(__dirname,'../public');
 const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');try{res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
 await new Promise(r=>server.listen(4173,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,...(process.env.TEST_BROWSER?{executablePath:process.env.TEST_BROWSER}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']});
 const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const getState=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('form-fitness-v1')));
 const waitHeading=async(text)=>{await page.getByRole('heading',{name:text,exact:true}).waitFor();};
 const screenshot=async(name)=>{if(process.env.TEST_SCREENSHOTS){fs.mkdirSync(process.env.TEST_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.TEST_SCREENSHOTS,name+'.png'),fullPage:true,animations:'disabled'});}};
 try{
 await page.goto('http://127.0.0.1:4173');await waitHeading('A stronger community.');await screenshot('dashboard');
 assert.equal(await page.locator('.stat-value').first().textContent(),'18');
 await page.getByRole('button',{name:'Add member',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 assert.equal(await page.locator('#full-name').evaluate(el=>el.validity.valueMissing),true);
 await page.getByLabel('Full name *',{exact:true}).fill('Alex Demo');
 await page.getByLabel('Email address *',{exact:true}).fill('miguel.santos@example.test');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 assert.match(await page.locator('#form-error').textContent(),/already belongs/);
 await page.getByLabel('Email address *',{exact:true}).fill('alex.demo@example.test');
 await page.getByLabel('Mobile number',{exact:true}).fill('09171234567');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.locator('input[name="plan"][value="plus"]').check();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.locator('#confirm-details').check();await screenshot('registration-review');
 await page.getByRole('button',{name:'Create member',exact:true}).click();await waitHeading('Member registered');
 let s=await getState();assert.equal(s.members.length,19);let member=s.members.find(m=>m.email==='alex.demo@example.test');assert.equal(member.plan,'plus');let inv=s.invoices.find(i=>i.memberId===member.id);assert.equal(inv.amount,1499);
 await page.getByRole('button',{name:'Record payment',exact:true}).click();
 await page.getByLabel('Amount (PHP) *',{exact:true}).fill('1500');await page.getByRole('button',{name:'Confirm payment',exact:true}).click();
 assert.equal(await page.locator('#amount').evaluate(el=>el.validity.rangeOverflow),true);
 await page.getByLabel('Amount (PHP) *',{exact:true}).fill('0');await page.getByRole('button',{name:'Confirm payment',exact:true}).click();
 assert.equal(await page.locator('#amount').evaluate(el=>el.validity.rangeUnderflow),true);
 await page.getByLabel('Amount (PHP) *',{exact:true}).fill('1000');
 await page.getByLabel('Reference (optional)',{exact:true}).fill('DEMO-PARTIAL');await page.getByRole('button',{name:'Confirm payment',exact:true}).click();await waitHeading('Payment recorded');
 assert.match(await page.locator('.success p').textContent(),/₱499 remains/);
 await page.getByRole('button',{name:'View receipt',exact:true}).click();await waitHeading('Payment receipt');
 const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download receipt',exact:true}).click();const dl=await dlPromise;assert.match(dl.suggestedFilename(),/^FORM-receipt-PAY-/);
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('link',{name:'Payments',exact:true}).click();await waitHeading('Every payment, in the clear.');
 await page.getByLabel('Search payments',{exact:true}).fill('Alex Demo');
 assert.equal(await page.locator('#payment-results tbody tr').count(),1);
 assert.match(await page.locator('#payment-results').textContent(),/Partial/);
 await page.locator('#payment-results').getByRole('button',{name:'Record payment',exact:true}).click();
 assert.equal(await page.locator('#amount').inputValue(),'499');
 await page.getByRole('button',{name:'Confirm payment',exact:true}).click();await waitHeading('Payment recorded');
 assert.match(await page.locator('.success p').textContent(),/status: active/);
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Member view',exact:true}).click();await waitHeading('Your next chapter, Alex.');
 assert.equal(await page.locator('.balance-amount').textContent(),'₱0');assert.equal(await page.locator('.membership-card .badge').textContent(),'Active');await screenshot('member-overview');
 await page.getByRole('button',{name:'View payment history',exact:true}).click();await waitHeading('Your payments, at a glance.');
 assert.equal(await page.locator('#payment-results tbody tr').count(),2);
 await page.getByRole('link',{name:'My membership',exact:true}).click();await page.getByRole('button',{name:'Select Performance',exact:true}).click();
 assert.match(await page.locator('.modal .notice').textContent(),/renewal preview/);await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Full name *',{exact:true}).fill('Alex Demo Updated');await page.getByRole('button',{name:'Save details',exact:true}).click();
 assert.match(await page.locator('.membership-card').textContent(),/Alex Demo Updated/);
 await page.reload();assert.equal((await getState()).members.length,19);
 await page.getByRole('button',{name:'Admin view',exact:true}).click();await waitHeading('A stronger community.');
 assert.equal(await page.locator('.stat-value').nth(1).textContent(),'13');
 await page.getByRole('button',{name:'View all members',exact:true}).click();await waitHeading('People make the progress.');
 await page.getByLabel('Search members',{exact:true}).fill('alex.demo');assert.equal(await page.locator('#member-results tbody tr').count(),1);assert.match(await page.locator('#member-results').textContent(),/Active/);
 let exportPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();assert.equal((await exportPromise).suggestedFilename(),'FORM-members.csv');
 await page.getByLabel('Search members',{exact:true}).fill('nobody matches this');assert.match(await page.locator('#member-results').textContent(),/No members found/);
 await page.getByRole('tab',{name:'Membership plans',exact:true}).click();assert.equal(await page.locator('.plan-card').count(),3);await screenshot('membership-plans');
 await page.getByRole('button',{name:'Class demo guide'}).click();await page.getByRole('button',{name:'Start with registration',exact:true}).click();await waitHeading('Welcome someone new.');await page.keyboard.press('Escape');assert.equal(await page.locator('[role="dialog"]').count(),0);
 // Future membership gets scheduled after full payment.
 await page.getByRole('button',{name:'Add member',exact:true}).click();await page.getByLabel('Full name *',{exact:true}).fill('Future Demo');await page.getByLabel('Email address *',{exact:true}).fill('future@example.test');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Membership start date *',{exact:true}).fill('2026-10-01');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('#confirm-details').check();await page.getByRole('button',{name:'Create member',exact:true}).click();await page.getByRole('button',{name:'Record payment',exact:true}).click();await page.getByRole('button',{name:'Confirm payment',exact:true}).click();assert.match(await page.locator('.success p').textContent(),/status: scheduled/);await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Reset demo data',exact:true}).click();await page.getByRole('button',{name:'Keep my changes',exact:true}).click();assert.equal((await getState()).members.length,20);
 await page.getByRole('button',{name:'Reset demo data',exact:true}).click();await page.locator('.modal').getByRole('button',{name:'Reset demo data',exact:true}).click();assert.equal((await getState()).members.length,18);
 await page.setViewportSize({width:390,height:844});await screenshot('mobile-dashboard');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('link',{name:'Members & plans'}).click();await waitHeading('People make the progress.');assert.equal(await page.locator('.sidebar.open').count(),0);
 await page.getByRole('button',{name:'Add member',exact:true}).click();assert.equal(await page.evaluate(()=>document.querySelector('.modal').getBoundingClientRect().right<=innerWidth),true);await screenshot('mobile-registration');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Member view',exact:true}).click();await screenshot('mobile-member');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:768,height:1024});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log('PASS: registration, required and duplicate validation, plan selection, partial/full/future payments, overpayment protection, receipts, member view, profile edits, reload persistence, directory search, exports, plan previews, guide, reset, mobile/tablet layouts. No browser JavaScript errors.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
